import requests

from flask import render_template, redirect, url_for, abort, request, flash
from flask.ext.mail import Message

from website import app, mail, g_secret, mail_default_recipients
from website.models.data import model
from website.models.form import ContactForm


@app.context_processor
def config_template():
    return dict(template="layout.html")


@app.errorhandler(404)
def page_not_found(e):
    return render_template("404.html"), 404


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/education")
def education():
    return render_template(
        "education.html",
        schools=model.get_schools(),
        projects=model.get_projects(),
    )


@app.route("/grades")
@app.route("/grades/<filename>")
def grades(filename=None):
    if filename is None:
        return render_template("grades.html")
    return render_template("grades.html", grades=model.get_document(filename))


@app.route("/resume")
def resume():
    return render_template("resume.html")


# NOTE: the use of 'other' is a temporary solution for POST forms compatibility with smoothState
@app.route("/contact", methods=["GET", "POST"])
@app.route("/contact/<string:other>", methods=["GET", "POST"])
def contact(other=None):
    form = ContactForm()
    if form.validate_on_submit():
        recaptcha_response = requests.post(
            "https://www.google.com/recaptcha/api/siteverify",
            data={"secret": g_secret, "response": request.form["g-recaptcha-response"]},
        )
        if recaptcha_response.json()["success"] == True:
            msg = Message(
                f"[PORTFOLIO] {form.obj.data}", recipients=mail_default_recipients
            )
            msg.html = f"""
                <i>This email has been generated by the portfolio website</i><br /><br />
                <b>Name: {form.name.data}</b><br />
                <b>Sender: {form.email.data}</b><br />
                <b>Object: {form.obj.data}</b><br />
                <br /><br />
                {form.text.data}
            """
            try:
                mail.send(msg)
                flash("Your message has been sent")
            except:
                flash("An internal error occured, your message has not been sent")
        else:
            flash("Are you a robot?")
    return render_template("contact.html", form=form, other=other)
